= Purple Hippo

Be it near or in a land far, far, away -– be it short or long ago as once ever was, Purple Hippo grew bored with the generous circumference of her purple-ness.
Therefore and by second-day free shipping, she caused many packages to arrive at the door.

Not long after, standing in front of the hall mirror, surrounded by open boxes, tissue paper, packing peanuts, and other intermediary stuff, Purple Hippo turned this way and that.
"`Now that’s more like it,`" she said, enjoying a freshly reinvigorated appreciation toward the reflection of her personage.
The feathers, the tutu, the lipstick… it was decided on the spot; a fashion debut was in order.

Answering her invitation came Bunyoro Rabbit, the Dik-Dik and Pygmy Hedgehog.
You see, somewhere along the way in drawing up her guest list Purple Hippo thought a test audience of little people might help her get better acclimated to the unfettered adulation of all Africa.

When invitations went out, it seems Mouse had been overlooked.
However, she showed up anyway and sat down on a pebble to see what it was about.

Once all were seated and appropriately hushed, Purple Hippo presented herself from behind a boulder.
With a delicate twist and turn, this way and that, she then thumped her foot upon the dusty red earth.
"`Now, little ones, tell me why I am so beautiful.`"

After a longish moment, Bunyoro Rabbit stood up.
Holding his chin in a most discerning way, he said, "`I was remarking just the other day how Purple Hippo’s feathers, long and majestic, are far more decorative than those of the famed Ostrich, who lives in the Great Yellow Plain beyond.
Isn’t that so!`"

Just so! All the small animals nodded.
Bunyoro Rabbit returned to his chair, twitching his astute tail.

The batting of Purple Hippo’s lashes was demure as the flutter of her pleasured giggle was sublime.
With a sweep and toss of her long peacock feathers, she deemed Bunyoro Rabbit true.

Next, they nudged Dik-Dik Antelope to stand.
Timid and shaky as a newborn on untried legs, he found just enough voice to squeak out: "`And at the water’s edge did I not ask all:`"Who else but our own Purple Hippo has such golden, blazing fierce, eyes?" A sudden shiver seized the Dik-Dik after his testimony, and he sat down with a plop.

Purple Hippo fixed her golden contact lenses upon the miniature antelope and gazed intently.
Seeing him shiver again, she deemed the Dik-Dik true.

Meanwhile, Pygmy Hedgehog was casting tender glances upon Mouse.
She sat prettily by and seemed to enjoy the pageant enormously, in her little way.

"`It is your turn, Pygmy Hedgehog,`" Purple Hippo rumbled.
"`Tell me what makes me so beautiful.
Stand.`"

"`I am standing,`" said Pygmy Hedgehog.

Everyone needed a moment to see.
Indeed, it was perfectly so.

"`Very well.
I am waiting,`" said Purple Hippo.

Pygmy Hedgehog stepped forward.
"`And earlier today I asked… who was it now I asked?`" he began, "`No matter who…, but I distinctly said when I first beheld Purple Hippo’s full red lips and, and… no one else can wear a tutu quite like… gah…`" Alas, his heart was not in it.
Pygmy Hedgehog turned instead to face Mouse, with his hand to his heart.
"`And you, Sister Mouse, have a wonderfulness all about you I could never embrace with mere words.`"

He bowed low to Mouse, and perhaps he even sat down.
It was so hard to tell.

The gathering of small animals around him had hushed in fear and trepidation.

Purple Hippo glowered.
She did not care the least bit for off-topic remarks made at the expense of her court and debut.
She tossed back her long feathers, fixed her golden gaze, and smacked her big red lips at Mouse.
"`Well, well, Sister Mouse, it seems you have found an admirer.
However, so far, I count three of my virtues to your one.
I am sorry, my dear.
With a little fixing up, maybe… I’d be glad to recommend a few things myself.`"

Mouse climbed down to leave, her smile already having gone elsewhere.

Now wasn’t everyone surprised to see Pygmy Hedgehog step boldly up to Purple Hippo? His heart certainly seemed to be in it this time.

"`Purple Hippo,`" he spoke clearly.
"`You are most extraordinarily arrayed with lips like red wine, the golden eyes of a lioness, and long lovely, need I say, exotic feathers – you might well be considered the most beautiful in all Africa, had you even the slightest thing in common with all this borrowed finery.`"

With that said, he excused himself while Purple Hippo was still working out whether it was a compliment or not.

So, my dear reader, sometimes that’s how the cookie crumbles.
The world is a vast place, after all.
News spread of Purple Hippo’s fashion debut as being distinctly lackluster, no matter where she took the show.
Eventually, she returned to lounging up to her ears and eyes in the green, green river – the firmly acknowledged queen of blowing bubbles.

You may be interested to know, Pygmy Hedgehog and Sister Mouse later hooked up and went on to live happily ever after in distant and ever-bohemian Jar-din du Luxembourg, Paris, France.

There they live to this day selling miniatures they paint on the riverfront.
It is a must do to buy one when you visit.
They are enormously popular

END
