== Purple Hippo

Be it near or in a land far, far, away — be it short or long ago as once ever was, Purple Hippo grew dissatisfied with the established order of purple bounteousness.
Therefore and by special order, she caused a package to come to her door.

In front of the hall mirror surrounded by discarded tissue paper, packing peanuts, and stuff, Purple Hippo turned this way and that.
She was enjoying a freshly reinvigorated appreciation toward the reflection of her personage.
“Now that’s more like it,” she said.
Decided on the spot, it was time for a fashion debut.

Answering the invitation, members of the smaller animal community began to arrive — among them, Bunyoro Rabbit, Dik-Dik Antelope, and Pygmy Hedgehog.
Mouse sat on a pebble and joined the party to see what it was about.

Once all had been seated and properly hushed, Purple Hippo presented herself with a delicate twist and turn, this way and that, and thumped her foot upon the dusty red earth.
“Now little ones, tell me why I am beautiful.”

After a long silence, Bunyoro Rabbit stood up.
Holding his chin in a most discerning attitude, he announced he’d never quite noticed before but Purple Hippo’s feathers, long and regal, were far more decorative than those of the famed Ostrich, who lives in the Great Yellow Plain beyond.

Just so! Everyone seemed to nod.
Bunyoro Rabbit returned to his chair, twitching his astute tail.

The batting of Purple Hippo’s lashes was demure, the flutter of her pleasured giggle, sublime.
With a sweeping flip of her long peacock feathers, she deemed Bunyoro Rabbit true.

Next, the nervous Dik-Dik Antelope was nudged to stand.
Timid and shaky as a newborn on untried legs he found just enough voice to squeak — he never quite noticed before, but Purple Hippo’s eyes were golden and riveting as the grass-crouching lion.
A quick shiver seized the Dik-Dik after his testimony and he sat down with a plop.

Purple Hippo fixed her contact lenses upon the miniature antelope and gazed intently.
Seeing him shiver again she deemed the Dik-Dik true.

Meanwhile, Pygmy Hedgehog was casting tender glances upon Mouse.
She sat prettily nearby, enjoying the pageant enormously.

“It is your turn, Pygmy Hedgehog,” Purple Hippo rumbled.
“Stand and tell me why I am beautiful.”

“I am standing!” said Pygmy Hedgehog.

Everyone needed a moment to see.
Indeed, it was entirely right.

“Well?” said Purple Hippo.

Pygmy Hedgehog stepped forward with his hand to his breast.
“I never quite noticed before,” he began, “but Purple Hippo’s lips are surely a finer red than pomegranate wine and…” But alas, his heart was not in it.
He turned to Mouse, instead.
“And you, Sister Mouse, have a truly beautiful smile.”

He bowed and perhaps even sat down.
It was so hard to tell.

Purple Hippo did not care the least bit for off-topic remarks made at the expense of her court and debut.
She tossed back her long feathers, fixed her golden gaze, and smacked her red lips at Mouse.
“Well, Sister Mouse it seems I have three to your one.
I am sorry my dear.
I am afraid it can’t be helped.”

Mouse climbed down to leave, her smile already having gone elsewhere.

But wasn’t everyone surprised to notice Pygmy Hedgehog taking a bold step forward? His heart certainly seemed to be in it this time.
“Purple Hippo,” he spoke bravely.
“You are most splendidly arrayed with lips like red wine, eyes of gold, and long exotic feathers — you might well be the most beautiful in all the land, had you even the smallest thing in common with this borrowed finery.”

So, dear reader, that’s how the cookie crumbles sometimes.
The world is a very big place after all.
Purple Hippo’s fashion reviews were consistently lackluster, no matter where she took her show.
She eventually returned to lounging up to her ears and eyes in the green, green river — the firmly acknowledged queen of blowing bubbles.

What’s more, you may be interested to know, Pygmy Hedgehog and Sister Mouse went on to live happily-ever-after in distant and ever-bohemian Jardin du Luxembourg Paris, France.
They live by the miniatures they paint on the riverfront and take leisurely long walks together — often leaning heavily on each other through times of laughter.

